### PR TITLE
Bump ERC1967 pragma to 0.8.4

### LINKED ISSUE #2979: ERC1967Upgrade.sol does not compile using Solidity 0.8.2
Hi OZ team, 

The following contract:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/52d42d6e03ba7940b78a4940ce13bca70aa4dacc/contracts/proxy/ERC1967/ERC1967Upgrade.sol#L16

Does not compile when using Solidity 0.8.2. The following error shows:

```
DocstringParsingError: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.
 --> @openzeppelin/contracts/proxy/ERC1967/ERC1967Upgrade.sol:9:1:
  |
9 | /**
  | ^ (Relevant source part starts here and spans across multiple lines).
Error HH600: Compilation failed
```

The error seems to have been reported, refer to this link: [Issue reported](https://github.com/ethereum/solidity/issues/11152)

I tried using Solidity 0.8.4 and compilation worked fine.

### PR DESCRIPTION
**Pull request by Amxx**
Fixes #2979 

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Comment by frangio** [comment]
I don't really understand, it looks like the current code compiles fine with 0.8.2. Can you confirm that this is necessary?

**Comment by Amxx** [comment]
In remix, with 0.8.2 selected, I am able to compile 
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/ERC1967/ERC1967Upgrade.sol";
```

**Comment by frangio** [comment]
Ok then if I understand correctly this can be closed.
