### ISSUE TITLE
ERC1967Upgrade.sol does not compile using Solidity 0.8.2

### ISSUE THREAD

**Issue by DaigaroCota** [OpenZeppelin/openzeppelin-contracts#2979]
Hi OZ team, 

The following contract:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/52d42d6e03ba7940b78a4940ce13bca70aa4dacc/contracts/proxy/ERC1967/ERC1967Upgrade.sol#L16

Does not compile when using Solidity 0.8.2. The following error shows:

```
DocstringParsingError: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.
 --> @openzeppelin/contracts/proxy/ERC1967/ERC1967Upgrade.sol:9:1:
  |
9 | /**
  | ^ (Relevant source part starts here and spans across multiple lines).
Error HH600: Compilation failed
```

The error seems to have been reported, refer to this link: [Issue reported](https://github.com/ethereum/solidity/issues/11152)

I tried using Solidity 0.8.4 and compilation worked fine.

**Comment by frangio** [comment]
Thank you @DaigaroCota. It seems we need to bump the pragma to 0.8.4.

**Comment by Amxx** [comment]
Hello @DaigaroCota 

While working on a fix for that, I was not able to replicate this issue. I am compiling using 0.8.2 on remix, and I'm not seeing any issue. Can you confirm this issue ?

**Comment by DaigaroCota** [comment]
Hi @Amxx,

I confirm it is an issue, though, perhaps it is specific to Hardhat. I tried compiling on Remix and it worked as you indicated. This makes me believe the issue is Hardhat specific then.

I set-up here: https://github.com/DaigaroCota/hardhat-playground/tree/test/issue/oz-erc1967-contract

Greeter.sol contract does not compile, displaying the error below:

![image](https://user-images.githubusercontent.com/32775237/146823194-be86201e-a289-4b52-ada8-7715bb314690.png)

Feel free to close issue here.

**Comment by frangio** [comment]
@DaigaroCota Thanks for the reproduction, but there is no dependency on `@openzeppelin/contracts` in that repository so we don't know what version you're using. I would recommend against installing the package globally if you've done that.
